
// <auto-generated>
using System.Reflection;
 
namespace FxResources.Microsoft.Extensions.Configuration.Binder
{
    internal static class SR { }
}
namespace System
{
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.Microsoft.Extensions.Configuration.Binder.SR)));

        /// <summary>Cannot create instance of type '{0}' because it is either abstract or an interface.</summary>
        internal static string @Error_CannotActivateAbstractOrInterface => GetResourceString("Error_CannotActivateAbstractOrInterface", @"Cannot create instance of type '{0}' because it is either abstract or an interface.");
        /// <summary>Failed to convert configuration value at '{0}' to type '{1}'.</summary>
        internal static string @Error_FailedBinding => GetResourceString("Error_FailedBinding", @"Failed to convert configuration value at '{0}' to type '{1}'.");
        /// <summary>Failed to create instance of type '{0}'.</summary>
        internal static string @Error_FailedToActivate => GetResourceString("Error_FailedToActivate", @"Failed to create instance of type '{0}'.");
        /// <summary>Cannot create instance of type '{0}' because it is missing a public parameterless constructor.</summary>
        internal static string @Error_MissingParameterlessConstructor => GetResourceString("Error_MissingParameterlessConstructor", @"Cannot create instance of type '{0}' because it is missing a public parameterless constructor.");
        /// <summary>Cannot create instance of type '{0}' because multidimensional arrays are not supported.</summary>
        internal static string @Error_UnsupportedMultidimensionalArray => GetResourceString("Error_UnsupportedMultidimensionalArray", @"Cannot create instance of type '{0}' because multidimensional arrays are not supported.");

    }
}